feat(CDN): add role icon endpoint
discordjs/discord.js-modules pull request #64
Opened 2021-09-22 07:24 UTC by iShibi

**Please describe the changes this PR makes and why it should be merged:**

- discord/discord-api-docs#3847

**Status and versioning classification:**
- I know how to update typings and have done so
- This PR changes the library's interface (methods or parameters added)

2021-09-28 07:25 UTC, kyranet submitted a review, later dismissed

2021-09-28 08:47 UTC, vladfrangu requested changes

2021-09-28 08:47 UTC, vladfrangu commented on packages/rest/src/lib/CDN.ts
> +	 * @param roleId The id of the role whose icon's URL is to be generated
```suggestion
	 * @param roleId The id of the role that has the icon
```

2021-09-28 08:47 UTC, vladfrangu commented on packages/rest/src/lib/CDN.ts
> +	 * @param options Optional data for the role icon
```suggestion
	 * @param options Optional options for the role icon
```

2021-09-28 09:25 UTC, vladfrangu approved these changes

2021-09-28 09:31 UTC, SpaceEEC approved these changes

2021-09-28 09:40 UTC, kyranet approved these changes

2021-10-02 21:55 UTC, iCrawl approved these changes

2021-10-02 21:55 UTC, merged