feat(RateLimits): optionally error on ratelimits
discordjs/discord.js-modules pull request #77
Opened 2021-10-25 08:00 UTC by ckohen

**Please describe the changes this PR makes and why it should be merged:**

Ported from https://github.com/discordjs/discord.js/pull/5659

~~Needs #51~~

**Status and versioning classification:**

- Code changes have been tested against the Discord API, or there are no code changes
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

2021-10-26 16:33 UTC, vladfrangu submitted a review, later dismissed

2021-10-30 10:35 UTC, ckohen commented
Not really sure why CI is failing (cache is set to npm when we're using yarn though, so maybe that's it?)

2021-10-30 10:43 UTC, iCrawl commented
That might just be my fault, yes 😆 
Will fix and then request a rebase.

2021-10-31 13:30 UTC, Jiralite commented on packages/rest/src/lib/REST.ts
> +	 * Determines how how rate limiting and pre-emptive throttling should be handled.
```suggestion
	 * Determines how rate limiting and pre-emptive throttling should be handled.
```

2021-10-31 13:30 UTC, Jiralite commented on packages/rest/src/lib/REST.ts
> +	 * for which to throw {@link RateLimitError}s. All other requests routes will be queued normally
```suggestion
	 * for which to throw {@link RateLimitError}s. All other request routes will be queued normally
```

2021-10-31 13:30 UTC, Jiralite commented on packages/rest/src/lib/REST.ts
> +	 * The full url for this request
```suggestion
	 * The full URL for this request
```

2021-11-02 13:18 UTC, kyranet submitted a review, later dismissed

2021-11-02 13:18 UTC, kyranet commented on packages/rest/__tests__/RequestHandler.test.ts
> +const rateLimitErrorApi = new REST({ rejectOnRateLimit: ['/channels'] }).setToken('Obviouslly-Not-A-Fake-Token');
```suggestion
const rateLimitErrorApi = new REST({ rejectOnRateLimit: ['/channels'] }).setToken('Obviously-Not-A-Fake-Token');
```

2021-11-13 09:19 UTC, kyranet submitted a review, later dismissed

2021-11-14 11:45 UTC, iCrawl submitted a review, later dismissed

2021-11-14 19:40 UTC, vladfrangu requested changes

2021-11-14 19:40 UTC, vladfrangu commented on packages/rest/src/lib/REST.ts
> +	 * (e.g. `/channels/` to match any route starting with `/channels` such as `/channels/:id/messages`)
```suggestion
	 * (e.g. `/channels` to match any route starting with `/channels` such as `/channels/:id/messages`)
```

2021-11-14 19:40 UTC, vladfrangu commented on packages/rest/src/lib/handlers/SequentialHandler.ts
> +				// Set RateLimitData based on the globl limit
```suggestion
				// Set RateLimitData based on the global limit
```

2021-11-15 04:49 UTC, iCrawl approved these changes

2021-11-24 16:54 UTC, kyranet approved these changes

2021-11-24 17:19 UTC, SpaceEEC approved these changes

2021-12-02 11:34 UTC, vladfrangu approved these changes

2021-12-02 14:04 UTC, merged